// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-noticias.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
var list_noticias_default = defineTool({
  name: "list_noticias",
  title: "Listar not\xEDcias APOGESP",
  description: "Lista as not\xEDcias publicadas no site da APOGESP, ordenadas da mais recente para a mais antiga.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("N\xFAmero m\xE1ximo de not\xEDcias (padr\xE3o 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("noticias").select("slug,titulo,resumo,autor,publicado_em").eq("publicado", true).order("publicado_em", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { noticias: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-noticia.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
var get_noticia_default = defineTool2({
  name: "get_noticia",
  title: "Ler not\xEDcia por slug",
  description: "Retorna o conte\xFAdo completo de uma not\xEDcia publicada da APOGESP pelo slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Slug da not\xEDcia (parte final da URL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("noticias").select("slug,titulo,resumo,conteudo,autor,publicado_em").eq("slug", slug).eq("publicado", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not\xEDcia n\xE3o encontrada." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { noticia: data }
    };
  }
});

// src/lib/mcp/tools/get-snapshot-carreira.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
var get_snapshot_carreira_default = defineTool3({
  name: "get_snapshot_carreira",
  title: "Snapshot da carreira APPGG",
  description: "Retorna os n\xFAmeros, indicadores e dados demogr\xE1ficos publicados da carreira de APPGG.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("snapshot_carreira").select("dados_publicado").eq("id", "current").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.dados_publicado ?? null, null, 2) }],
      structuredContent: { snapshot: data?.dados_publicado ?? null }
    };
  }
});

// src/lib/mcp/tools/list-publicacoes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
var list_publicacoes_default = defineTool4({
  name: "list_publicacoes",
  title: "Listar publica\xE7\xF5es",
  description: "Lista as publica\xE7\xF5es institucionais da APOGESP (estudos, notas t\xE9cnicas, boletins).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("publicacoes_itens").select("dados_publicado,ordem").eq("publicado", true).eq("deletado", false).not("dados_publicado", "is", null).order("ordem", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (data ?? []).map((r) => r.dados_publicado);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { publicacoes: items }
    };
  }
});

// src/lib/mcp/tools/list-wiki-verbetes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.4";
function supabaseForUser(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wiki_verbetes_default = defineTool5({
  name: "list_wiki_verbetes",
  title: "Wiki da Carreira \u2014 verbetes",
  description: "Lista os verbetes publicados da Wiki da Carreira (\xC1rea do Associado). Requer que o usu\xE1rio esteja autenticado como associado.",
  inputSchema: {
    slug: z3.string().optional().describe("Se informado, retorna apenas o verbete com este slug (incluindo conte\xFAdo).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Autentica\xE7\xE3o necess\xE1ria. Fa\xE7a login como associado APOGESP." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("wiki_verbetes").select("dados_publicado,ordem").eq("publicado", true).eq("deletado", false).not("dados_publicado", "is", null).order("ordem", { ascending: true });
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let items = (data ?? []).map((r) => r.dados_publicado);
    if (slug) items = items.filter((v) => v?.slug === slug);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { verbetes: items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mwwuqrbxoxpcqyuvmvsu";
var mcp_default = defineMcp({
  name: "apogesp-mcp",
  title: "APOGESP",
  version: "0.1.0",
  instructions: "Ferramentas oficiais da APOGESP (Associa\xE7\xE3o dos Analistas de Pol\xEDticas P\xFAblicas e Gest\xE3o Governamental de S\xE3o Paulo). Use list_noticias e get_noticia para acessar not\xEDcias p\xFAblicas, get_snapshot_carreira para dados da carreira APPGG, list_publicacoes para publica\xE7\xF5es institucionais, e list_wiki_verbetes (requer login de associado) para a Wiki da Carreira.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_noticias_default, get_noticia_default, get_snapshot_carreira_default, list_publicacoes_default, list_wiki_verbetes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
