insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.hero.label', 'apogesp', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Institucional$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.hero.titulo', 'apogesp', 1, 'text', $TXT$Hero — título$TXT$, $TXT$A APOGESP$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.hero.subtitulo', 'apogesp', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$A voz coletiva de quem dedica a carreira a fazer a gestão pública de São Paulo funcionar melhor.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.quem-somos.label', 'apogesp', 3, 'text', $TXT$Quem somos — eyebrow$TXT$, $TXT$Sobre$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.quem-somos.titulo', 'apogesp', 4, 'text', $TXT$Quem somos — título$TXT$, $TXT$Quem Somos$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.quem-somos.texto', 'apogesp', 5, 'markdown', $TXT$Quem somos — parágrafos$TXT$, $TXT$A APOGESP nasceu de uma convicção simples: profissionais que compartilham uma missão precisam de um espaço para pensar juntos. Como entidade representativa dos Analistas de Políticas Públicas e Gestão Governamental do Município de São Paulo, a associação existe para amplificar o impacto coletivo da carreira.

A APOGESP é uma entidade civil, sem fins lucrativos, independente de governo e de partidos. Sua atuação se organiza em três frentes: valorização da carreira, produção de conhecimento sobre gestão municipal e interlocução com órgãos públicos, entidades parceiras e sociedade civil.

A independência da APOGESP é condição para sua relevância. É ela que permite à associação dialogar com diferentes governos, propor aprimoramentos à carreira com franqueza e produzir análises técnicas sem constrangimentos institucionais. A APOGESP fala em nome dos seus associados — e só deles.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.missao.label', 'apogesp', 6, 'text', $TXT$Missão — eyebrow$TXT$, $TXT$Propósito$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.missao.titulo', 'apogesp', 7, 'text', $TXT$Missão — título$TXT$, $TXT$Missão$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.missao.texto', 'apogesp', 8, 'markdown', $TXT$Missão — texto$TXT$, $TXT$Fortalecer a carreira de APPGG e contribuir para o aprimoramento da gestão pública no município de São Paulo — não com discursos, mas com produção técnica, representação institucional qualificada, articulação entre setores e investimento permanente em capacidades estatais. A missão da APOGESP é garantir que a experiência acumulada por seus integrantes se converta em memória, método e legado.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.objetivos.label', 'apogesp', 9, 'text', $TXT$Objetivos — eyebrow$TXT$, $TXT$Diretrizes$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.objetivos.titulo', 'apogesp', 10, 'text', $TXT$Objetivos — título$TXT$, $TXT$Objetivos$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.diretoria.label', 'apogesp', 11, 'text', $TXT$Diretoria — eyebrow$TXT$, $TXT$Gestão$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.diretoria.titulo', 'apogesp', 12, 'text', $TXT$Diretoria — título$TXT$, $TXT$Diretoria$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.independente.label', 'apogesp', 13, 'text', $TXT$Independente — eyebrow$TXT$, $TXT$Posicionamento$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.independente.titulo', 'apogesp', 14, 'text', $TXT$Independente — título$TXT$, $TXT$Uma Entidade Independente$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('apogesp.independente.texto', 'apogesp', 15, 'markdown', $TXT$Independente — parágrafos$TXT$, $TXT$A carreira de APPGG foi criada em 2015 e seus integrantes atuam vinculados à estrutura administrativa da Prefeitura de São Paulo. A APOGESP, por sua vez, é uma associação civil sem fins lucrativos, independente e autônoma — não integra a estrutura administrativa da Prefeitura, não depende do governo e não fala por ele.

Essa separação é deliberada. A APOGESP é, antes de tudo, uma entidade de representação dos interesses de classe dos APPGGs — atua pela valorização da carreira, pela defesa de condições adequadas de trabalho e pelo reconhecimento institucional de seus associados. Ao mesmo tempo, pretende contribuir com o debate público sobre gestão municipal, produzindo conhecimento técnico e mantendo um canal de diálogo permanente com a administração pública.

A APOGESP reconhece e valoriza o trabalho das instâncias governamentais responsáveis pela gestão da carreira, mas preserva sua autonomia para analisar, propor e, quando necessário, divergir. É essa independência que sustenta a credibilidade da associação perante seus associados e a sociedade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.hero.label', 'carreira', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$A Carreira$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.hero.titulo', 'carreira', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Analistas de Políticas Públicas e Gestão Governamental$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.hero.subtitulo', 'carreira', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$A carreira que colabora — em conjunto com outras carreiras municipais e dentro das diretrizes da administração superior — para que São Paulo transforme intenções em entregas que mudam a realidade e promovem uma cidade mais pujante, justa e democrática.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.intro.label', 'carreira', 3, 'text', $TXT$Intro — eyebrow$TXT$, $TXT$Sobre$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.intro.titulo', 'carreira', 4, 'text', $TXT$Intro — título$TXT$, $TXT$O que é a carreira$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.intro.texto', 'carreira', 5, 'markdown', $TXT$Intro — parágrafos$TXT$, $TXT$Em 2015, o município de São Paulo fez uma aposta: criar uma carreira de nível superior dedicada a colaborar com o fortalecimento da capacidade do governo municipal de planejar, implementar e avaliar políticas públicas. A Lei Municipal nº 16.193 deu nome a essa aposta — Analista de Políticas Públicas e Gestão Governamental — e definiu suas atribuições: implementação, supervisão, coordenação, execução, monitoramento e avaliação de projetos, atividades e políticas públicas, sempre em apoio às prioridades fixadas pela administração superior.

Uma década depois, os frutos dessa decisão estão espalhados por toda a administração — sempre como produto de um trabalho conjunto. Os APPGGs colaboram, lado a lado com outras carreiras municipais e com as lideranças de cada pasta, na intersecção entre a formulação técnica e a realidade do território.

A carreira atua na chamada burocracia de médio escalão: o espaço entre quem decide e quem executa. É ali que se contribui para traduzir diretrizes em projetos, indicadores em ações e compromissos em entregas mensuráveis — sempre em diálogo com as equipes técnicas, gestores e parceiros institucionais que conduzem cada iniciativa.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.citacao.frase', 'carreira', 6, 'markdown', $TXT$Citação$TXT$, $TXT$A força da carreira está em colaborar, dentro da legalidade e das prioridades da administração superior, para que cada política pública chegue ao cidadão com técnica, integridade e continuidade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.citacao.autor', 'carreira', 7, 'text', $TXT$Citação — autor$TXT$, $TXT$Odilon A. Candido — Diretor Jurídico da APOGESP$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.perfil.label', 'carreira', 8, 'text', $TXT$Perfil — eyebrow$TXT$, $TXT$Perfil$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.perfil.titulo', 'carreira', 9, 'text', $TXT$Perfil — título$TXT$, $TXT$Quem São os APPGGs$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.perfil.texto', 'carreira', 10, 'markdown', $TXT$Perfil — parágrafos$TXT$, $TXT$Administradores públicos, economistas, cientistas sociais, engenheiros, advogados — os APPGGs chegam de formações diversas, mas convergem em uma competência comum: a capacidade de traduzir problemas complexos em decisões implementáveis. O ingresso ocorre por concurso público de provas e títulos, exigindo nível superior.

Na prática, os analistas atuam como intérpretes — de problemas públicos, de dados, de contextos políticos e institucionais. Em diálogo com as equipes técnicas e com as lideranças de cada órgão, contribuem para identificar lacunas entre a diretriz e sua execução e participam da construção do caminho para preenchê-las. Ferramentas de gestão e planejamento são o vocabulário; a colaboração com a melhoria das políticas públicas, o objetivo.

O trabalho vai além da técnica isolada. APPGGs participam de projetos, contribuem com a formação de novas lideranças, colaboram com laboratórios de inovação, apoiam o redesenho de processos e enfrentam — sempre em conjunto com outras carreiras e dentro dos Planos de Atuação Institucional — problemas que nenhum manual previu.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.areas.label', 'carreira', 11, 'text', $TXT$Áreas — eyebrow$TXT$, $TXT$Competências$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.areas.titulo', 'carreira', 12, 'text', $TXT$Áreas — título$TXT$, $TXT$Áreas de Atuação$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.memoria.label', 'carreira', 13, 'text', $TXT$Memória — eyebrow$TXT$, $TXT$Continuidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.memoria.titulo', 'carreira', 14, 'text', $TXT$Memória — título$TXT$, $TXT$Memória Institucional das Políticas Públicas$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.memoria.texto', 'carreira', 15, 'markdown', $TXT$Memória — parágrafos$TXT$, $TXT$Governos passam, ciclos políticos se sucedem, secretários chegam e partem. O que permanece — e o que sustenta a capacidade de São Paulo de governar a si mesma — é o conhecimento acumulado sobre como cada política pública foi pensada, executada e revisada ao longo do tempo. Os APPGGs são, em larga medida, responsáveis por preservar essa continuidade.

Por estarem distribuídos nas secretarias, nos órgãos de planejamento, nos sistemas de monitoramento e nos projetos estratégicos, os analistas registram, documentam e preservam a trajetória das decisões: o que motivou determinada escolha, quais alternativas foram descartadas, quais entregas funcionaram, quais aprendizados ficaram. É uma memória técnica que não cabe em um único arquivo, mas que vive nas equipes, nos processos e nos sistemas que a carreira ajuda a construir.

Essa função silenciosa — costurar passado, presente e futuro das políticas públicas municipais — é o que permite que cada nova gestão encontre, ao chegar, não uma página em branco, mas um repertório vivo. Preservar essa memória é, também, preservar o direito da cidade de aprender com a própria história.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.cronologia.label', 'carreira', 16, 'text', $TXT$Cronologia — eyebrow$TXT$, $TXT$Cronologia$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.cronologia.titulo', 'carreira', 17, 'text', $TXT$Cronologia — título$TXT$, $TXT$Uma Década em Construção$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.numeros.label', 'carreira', 18, 'text', $TXT$Números — eyebrow$TXT$, $TXT$Dados$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.numeros.titulo', 'carreira', 19, 'text', $TXT$Números — título$TXT$, $TXT$APPGGs em Números$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.numeros.legenda', 'carreira', 20, 'text', $TXT$Números — legenda$TXT$, $TXT$Snapshot fevereiro de 2026$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.legal.label', 'carreira', 21, 'text', $TXT$Marco legal — eyebrow$TXT$, $TXT$Legislação$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.legal.titulo', 'carreira', 22, 'text', $TXT$Marco legal — título$TXT$, $TXT$Marco Legal$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('carreira.legal.texto', 'carreira', 23, 'markdown', $TXT$Marco legal — parágrafos$TXT$, $TXT$A base legal da carreira está no artigo 13 da Lei nº 16.193/2015, que define suas atribuições como: *“implementação, supervisão, coordenação, execução, monitoramento e avaliação de projetos, atividades e políticas públicas da Administração Direta e Indireta da Prefeitura do Município de São Paulo.”* Poucas carreiras municipais no Brasil têm um mandato tão amplo — e tão exigente.

Em 2021, a Portaria SEGES nº 13 deu o próximo passo: formalizou que os APPGGs devem ser alocados prioritariamente em apoio à elaboração do Programa de Metas, ao planejamento orçamentário (LOA e PPA) e a projetos de reestruturação institucional, sempre conforme as prioridades definidas pela administração superior.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.hero.label', 'atuacao', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Colaboração$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.hero.titulo', 'atuacao', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Atuação dos APPGGs$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.hero.subtitulo', 'atuacao', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Mais de 50 casos de colaboração de Analistas de Políticas Públicas e Gestão Governamental com órgãos e equipes da Prefeitura de São Paulo. Do Caderno Gestão Pública em Rede ao 2º Seminário APPGG.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.casos.label', 'atuacao', 3, 'text', $TXT$Casos — eyebrow$TXT$, $TXT$Casos Documentados$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.casos.titulo', 'atuacao', 4, 'text', $TXT$Casos — título$TXT$, $TXT$Onde a Carreira Colaborou$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.casos.subtitulo', 'atuacao', 5, 'text', $TXT$Casos — subtítulo$TXT$, $TXT$Cada caso abaixo registra contribuições de APPGGs em iniciativas conduzidas em conjunto com outras carreiras, gestores e parceiros institucionais, dentro das prioridades fixadas pela administração superior.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.eixos.label', 'atuacao', 6, 'text', $TXT$Eixos — eyebrow$TXT$, $TXT$Vocação$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.eixos.titulo', 'atuacao', 7, 'text', $TXT$Eixos — título$TXT$, $TXT$Os Três Eixos da Colaboração$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('atuacao.cta.texto', 'atuacao', 8, 'text', $TXT$CTA — texto$TXT$, $TXT$Conheça os Planos de Atuação Institucional de cada órgão$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.hero.label', 'contato', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Fale Conosco$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.hero.titulo', 'contato', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Contato$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.hero.subtitulo', 'contato', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Se você é servidor, pesquisador, gestor ou cidadão interessado em gestão pública municipal, este é o canal.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.info.label', 'contato', 3, 'text', $TXT$Info — eyebrow$TXT$, $TXT$Informações$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.info.titulo', 'contato', 4, 'text', $TXT$Info — título$TXT$, $TXT$Como nos encontrar$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.info.email', 'contato', 5, 'text', $TXT$E-mail$TXT$, $TXT$apogesp@gmail.com$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.info.localizacao', 'contato', 6, 'text', $TXT$Localização$TXT$, $TXT$São Paulo — SP, Brasil$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('contato.info.texto', 'contato', 7, 'markdown', $TXT$Info — texto final$TXT$, $TXT$A APOGESP recebe mensagens de associados, gestores públicos, pesquisadores, jornalistas e de qualquer cidadão interessado na carreira de APPGG e na gestão pública municipal de São Paulo. Respondemos em até cinco dias úteis.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.hero.label', 'diversidade', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Diversidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.hero.titulo', 'diversidade', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Representar a cidade ainda é uma agenda em disputa$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.hero.subtitulo', 'diversidade', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$A APOGESP olha para a composição da carreira sem complacência. Os números mostram avanços, mas também distâncias persistentes em relação à cidade que administramos — e oscilações entre concursos que contradizem qualquer narrativa de progresso automático. Diversidade não se corrige por inércia: depende de regras de ingresso, critérios de promoção, abertura a posições decisórias e disposição institucional para revisar o que está naturalizado.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.panorama.label', 'diversidade', 3, 'text', $TXT$Panorama — eyebrow$TXT$, $TXT$Panorama$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.panorama.titulo', 'diversidade', 4, 'text', $TXT$Panorama — título$TXT$, $TXT$O retrato — e o que ele cobra$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.label', 'diversidade', 5, 'text', $TXT$Contexto — eyebrow$TXT$, $TXT$Contexto$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.titulo', 'diversidade', 6, 'text', $TXT$Contexto — título$TXT$, $TXT$A neutralidade administrativa é uma ficção conveniente$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.subtitulo', 'diversidade', 7, 'text', $TXT$Contexto — subtítulo$TXT$, $TXT$Critérios de elegibilidade, modelos de atendimento, fluxos de aprovação e bases de dados raramente são neutros em seus efeitos. Quando o corpo técnico que os formula reproduz uma única perspectiva social, a administração tende a confundir suas próprias zonas cegas com universalidade — e a tratar como exceção o que é, na verdade, exclusão sistemática.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.bloco1-titulo', 'diversidade', 8, 'text', $TXT$Contexto — bloco 1 título$TXT$, $TXT$Exclusão sem autoria explícita$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.bloco1-texto', 'diversidade', 9, 'markdown', $TXT$Contexto — bloco 1 texto$TXT$, $TXT$Políticas públicas não falham apenas por má-fé ou subfinanciamento. Falham, com frequência, em decisões aparentemente técnicas: o documento exigido, o canal eleito como padrão, o horário de atendimento, o indicador escolhido para medir sucesso. Cada uma dessas escolhas filtra quem acessa, quem é contado e quem permanece invisível. Sem diversidade no desenho, o filtro opera no automático.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.bloco2-titulo', 'diversidade', 10, 'text', $TXT$Contexto — bloco 2 título$TXT$, $TXT$Onde a diretriz se perde$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.bloco2-texto', 'diversidade', 11, 'markdown', $TXT$Contexto — bloco 2 texto$TXT$, $TXT$Entre o discurso de equidade e o efeito concreto no território existe uma cadeia longa de decisões técnicas. É nessa cadeia — operada por gestores como o APPGG — que prioridades viram procedimentos e procedimentos viram acesso (ou barreira). Tratar essa camada como neutra é o que permite que governos defendam pautas progressistas enquanto suas burocracias seguem produzindo desigualdade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.contexto.destaque', 'diversidade', 12, 'markdown', $TXT$Contexto — destaque$TXT$, $TXT$Para a APOGESP, burocracia representativa não é concessão simbólica nem cota a tolerar. É uma exigência técnica: ampliar repertórios de análise no Estado é o que permite identificar exclusões antes que elas se consolidem em política pública.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.atuacao.label', 'diversidade', 13, 'text', $TXT$Atuação — eyebrow$TXT$, $TXT$Atuação estratégica$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.atuacao.titulo', 'diversidade', 14, 'text', $TXT$Atuação — título$TXT$, $TXT$Onde o APPGG faz diferença$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.atuacao.subtitulo', 'diversidade', 15, 'text', $TXT$Atuação — subtítulo$TXT$, $TXT$O APPGG não apenas executa políticas. Ele desenha, ajusta, mede e corrige. Em cada uma dessas funções, diversidade e capacidade técnica podem se reforçar mutuamente.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.lideranca.label', 'diversidade', 16, 'text', $TXT$Liderança — eyebrow$TXT$, $TXT$Liderança$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.lideranca.titulo', 'diversidade', 17, 'text', $TXT$Liderança — título$TXT$, $TXT$Quem decide ainda não reflete quem entra$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.lideranca.subtitulo', 'diversidade', 18, 'text', $TXT$Liderança — subtítulo$TXT$, $TXT$A presença de mulheres e pessoas negras em cargos de liderança é um dos testes mais duros da maturidade institucional. Os números abaixo mostram avanços relativos — mulheres e pessoas negras estão proporcionalmente mais presentes na liderança do que na carreira como um todo. Mas isso não autoriza autocomplacência: liderança ainda é majoritariamente branca e masculina, e o acesso a essas posições segue dependente de redes informais que a APOGESP entende como objeto legítimo de escrutínio.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.evolucao.label', 'diversidade', 19, 'text', $TXT$Evolução — eyebrow$TXT$, $TXT$Evolução$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.evolucao.titulo', 'diversidade', 20, 'text', $TXT$Evolução — título$TXT$, $TXT$O progresso não é linear — e os dados mostram$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.evolucao.subtitulo', 'diversidade', 21, 'text', $TXT$Evolução — subtítulo$TXT$, $TXT$A leitura honesta das coortes desautoriza qualquer narrativa de avanço automático. A representatividade racial caiu da geração pioneira (37,5%) para os concursos de 2021–2022 (29,2%) e 2024 (25,5%), recuperando-se em parte em 2026 (35,3%) — ainda abaixo do patamar inicial e muito distante da composição racial da cidade. Cada concurso é uma decisão política sobre quem o Estado escolhe formar.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.evolucao.destaque', 'diversidade', 22, 'markdown', $TXT$Evolução — destaque$TXT$, $TXT$A oscilação entre coortes não é detalhe estatístico: é evidência de que regras de seleção, políticas afirmativas, formato das provas e critérios de pontuação produzem efeitos diretos e mensuráveis na composição do serviço público. Tratar a diversidade do ingresso como agenda permanente — e não como bandeira a hastear em ano par — é responsabilidade institucional. A APOGESP cobra essa continuidade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.presenca.label', 'diversidade', 23, 'text', $TXT$Presença — eyebrow$TXT$, $TXT$Presença institucional$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.presenca.titulo', 'diversidade', 24, 'text', $TXT$Presença — título$TXT$, $TXT$Distribuição desigual entre os órgãos$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.presenca.destaque', 'diversidade', 25, 'markdown', $TXT$Presença — destaque$TXT$, $TXT$Distribuição importa porque concentração é, por definição, ausência em outro lugar. Acompanhar onde a diversidade está — e onde ela falta — é parte do trabalho de uma associação que leva a sério a representatividade do corpo técnico que ajuda a decidir o orçamento, o planejamento e as políticas da cidade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.fechamento.label', 'diversidade', 26, 'text', $TXT$Fechamento — eyebrow$TXT$, $TXT$Posição da APOGESP$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.fechamento.titulo', 'diversidade', 27, 'text', $TXT$Fechamento — título$TXT$, $TXT$Reconhecer o avanço sem dispensar a cobrança$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('diversidade.fechamento.texto', 'diversidade', 28, 'markdown', $TXT$Fechamento — parágrafos$TXT$, $TXT$Os dados desta página descrevem uma carreira que avançou — e que segue devendo. A presença de mulheres e de pessoas negras melhorou em relação a outras carreiras de Estado, mas continua aquém da composição de São Paulo. A inclusão de pessoas com deficiência permanece marginal. A liderança ainda é majoritariamente branca e masculina. E o ingresso, longe de uma trajetória ascendente, oscila concurso a concurso, em função de regras que mudam, políticas afirmativas que enfraquecem e prioridades que se deslocam.

A APOGESP rejeita duas posições igualmente confortáveis: celebrar conquistas como se estivessem consolidadas e diagnosticar problemas como se fossem inevitáveis. Diversidade na carreira não é favor concedido pela administração nem ornamento de relatório institucional — é condição para que o Estado enxergue a cidade que pretende governar.

Continuaremos publicando os dados, apontando os retrocessos, defendendo políticas afirmativas robustas no ingresso e cobrando que o acesso a posições de liderança siga critérios técnicos verificáveis. Representar os APPGGs também é representar a expectativa pública de que essa carreira se pareça, cada vez mais, com a São Paulo que serve.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.hero.label', 'sustentabilidade', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Meio Ambiente$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.hero.titulo', 'sustentabilidade', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Sustentabilidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.hero.subtitulo', 'sustentabilidade', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Como os APPGGs colaboram com a construção de uma São Paulo mais sustentável, sempre em parceria com outras carreiras e dentro das diretrizes da administração superior.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.intro.texto', 'sustentabilidade', 3, 'markdown', $TXT$Intro — parágrafos$TXT$, $TXT$São Paulo é a maior metrópole da América Latina — e também uma das mais vulneráveis às mudanças climáticas. Enchentes, ilhas de calor, crises hídricas e poluição atmosférica são desafios que exigem políticas públicas sofisticadas, baseadas em evidências e com visão de longo prazo.

Nesse cenário, os Analistas de Políticas Públicas e Gestão Governamental colaboram com diferentes secretarias para apoiar a tradução dos compromissos ambientais em programas concretos, indicadores mensuráveis e governança efetiva. Da Secretaria do Verde e Meio Ambiente à Secretaria de Infraestrutura Urbana, APPGGs participam — junto a equipes técnicas de outras carreiras e às lideranças setoriais — de iniciativas pactuadas nos Planos de Atuação Institucional.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.eixos.label', 'sustentabilidade', 4, 'text', $TXT$Eixos — eyebrow$TXT$, $TXT$Eixos Temáticos$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.eixos.titulo', 'sustentabilidade', 5, 'text', $TXT$Eixos — título$TXT$, $TXT$Onde os APPGGs colaboram com a sustentabilidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.visao.label', 'sustentabilidade', 6, 'text', $TXT$Visão — eyebrow$TXT$, $TXT$Perspectiva$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.visao.titulo', 'sustentabilidade', 7, 'text', $TXT$Visão — título$TXT$, $TXT$Uma cidade que planeja seu futuro$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.visao.texto', 'sustentabilidade', 8, 'markdown', $TXT$Visão — texto$TXT$, $TXT$A agenda ambiental não é um tema isolado — ela atravessa todas as áreas da gestão pública. Saúde, mobilidade, habitação, educação: cada política setorial tem uma dimensão ambiental que precisa ser considerada. Os APPGGs, por sua formação transversal e capacidade de articulação, colaboram — em conjunto com as carreiras técnicas finalísticas e sob coordenação das lideranças de cada pasta — para que a sustentabilidade seja tratada como eixo estruturante dentro dos Planos de Atuação Institucional.

Com o avanço das metas climáticas globais e os compromissos assumidos por São Paulo em fóruns internacionais, a demanda por trabalho colaborativo e qualificado na área ambiental só tende a crescer. Fortalecer a carreira de APPGG é também fortalecer a capacidade do município de responder, em parceria entre carreiras, aos maiores desafios do nosso tempo.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.cta.texto', 'sustentabilidade', 9, 'text', $TXT$CTA — texto$TXT$, $TXT$Conheça os Planos de Atuação Institucional dos órgãos com projetos ambientais$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('sustentabilidade.cta.link', 'sustentabilidade', 10, 'text', $TXT$CTA — link label$TXT$, $TXT$Ver Planos de Atuação Ambientais$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.hero.label', 'campanha-salarial', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Campanha 2026$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.hero.titulo', 'campanha-salarial', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Remuneração Justa para Quem Constrói a Cidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.hero.subtitulo', 'campanha-salarial', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Uma carreira estratégica não sobrevive com remuneração defasada. Conheça os números, compare com o governo federal e com outros municípios — e entenda por que a recomposição salarial dos APPGGs é urgente.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.problema.label', 'campanha-salarial', 3, 'text', $TXT$Problema — eyebrow$TXT$, $TXT$O Problema$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.problema.titulo', 'campanha-salarial', 4, 'text', $TXT$Problema — título$TXT$, $TXT$Uma Década Sem Equiparação$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.problema.subtitulo', 'campanha-salarial', 5, 'text', $TXT$Problema — subtítulo$TXT$, $TXT$Em 2015, a carreira de APPGG foi criada como espelho municipal do EPPGG federal. Dez anos depois, a remuneração não acompanhou — nem o governo federal, nem municípios como Niterói.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.comparativo.label', 'campanha-salarial', 6, 'text', $TXT$Comparativo — eyebrow$TXT$, $TXT$Comparativo$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.comparativo.titulo', 'campanha-salarial', 7, 'text', $TXT$Comparativo — título$TXT$, $TXT$O Mesmo Trabalho, Três Realidades$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.comparativo.subtitulo', 'campanha-salarial', 8, 'text', $TXT$Comparativo — subtítulo$TXT$, $TXT$Remuneração por nível de progressão na carreira. APPGG (São Paulo), EPPGG (Federal, 2026) e APPGG (Niterói, com gratificação de 50%).$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.comparativo.fontes', 'campanha-salarial', 9, 'text', $TXT$Comparativo — fontes$TXT$, $TXT$Fontes: Lei nº 18.235/2025 (APPGG SP); MP nº 1.286/2024 (EPPGG Federal); Diário Oficial de Niterói, 28/11/2025 (APPGG Niterói, com gratificação de desempenho de 50%).$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.comparativo.sintese', 'campanha-salarial', 10, 'markdown', $TXT$Comparativo — síntese$TXT$, $TXT$O APPGG de São Paulo — maior metrópole da América Latina — recebe **27% menos** que o cargo equivalente em Niterói e **34% menos** que o EPPGG federal no início da carreira. No topo, a defasagem frente ao governo federal chega a **56%**.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.cta.frase', 'campanha-salarial', 11, 'text', $TXT$CTA — frase$TXT$, $TXT$Não se trata de privilégio. Trata-se de reter os profissionais que a cidade precisa para funcionar.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.cta.assinatura', 'campanha-salarial', 12, 'text', $TXT$CTA — assinatura$TXT$, $TXT$APOGESP — Campanha Salarial 2026$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-salarial.cta.link', 'campanha-salarial', 13, 'text', $TXT$CTA — link$TXT$, $TXT$Apoie a campanha$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.hero.label', 'campanha-nomeacao', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Nomeação Já$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.hero.titulo', 'campanha-nomeacao', 1, 'text', $TXT$Hero — título$TXT$, $TXT$53 Aprovados. Zero Razões Para Esperar.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.hero.subtitulo', 'campanha-nomeacao', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Um concurso com 242 candidatos por vaga selecionou os melhores. 80 já servem a cidade. Faltam 53 — e 102 cargos vagos esperando por eles.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.narrativa.texto', 'campanha-nomeacao', 3, 'markdown', $TXT$Narrativa — parágrafos$TXT$, $TXT$Em 2023, a Lei nº 17.913 ampliou o quadro de APPGGs para **300 cargos** — um reconhecimento de que São Paulo precisa de mais analistas de gestão. Hoje, **102 desses cargos estão vagos**. Um terço da capacidade projetada simplesmente não existe.

Enquanto isso, 53 profissionais aprovados no concurso mais competitivo da história da carreira — **242 candidatos por vaga** — aguardam nomeação. São pessoas com formação em universidades de referência, experiência combinada nos setores público e privado, e domínio de ferramentas analíticas que a administração precisa.

O custo da nomeação é marginal frente ao orçamento municipal. Não nomear é aceitar que secretarias continuem operando abaixo da capacidade, que projetos estratégicos percam qualidade técnica e que a prefeitura perca competitividade na atração de talentos frente ao governo federal e ao setor privado.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.porque.label', 'campanha-nomeacao', 4, 'text', $TXT$Por que — eyebrow$TXT$, $TXT$O Cenário$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.porque.titulo', 'campanha-nomeacao', 5, 'text', $TXT$Por que — título$TXT$, $TXT$Por Que Nomear Agora$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.numeros.label', 'campanha-nomeacao', 6, 'text', $TXT$Números — eyebrow$TXT$, $TXT$Em Números$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.numeros.titulo', 'campanha-nomeacao', 7, 'text', $TXT$Números — título$TXT$, $TXT$O Quadro Atual$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.perfil.label', 'campanha-nomeacao', 8, 'text', $TXT$Perfil — eyebrow$TXT$, $TXT$Capital Humano$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.perfil.titulo', 'campanha-nomeacao', 9, 'text', $TXT$Perfil — título$TXT$, $TXT$Quem São os 53 Aprovados$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.perfil.subtitulo', 'campanha-nomeacao', 10, 'text', $TXT$Perfil — subtítulo$TXT$, $TXT$Profissionais selecionados no concurso mais competitivo da carreira, com formação multidisciplinar e experiência comprovada.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.timeline.label', 'campanha-nomeacao', 11, 'text', $TXT$Timeline — eyebrow$TXT$, $TXT$Processo$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.timeline.titulo', 'campanha-nomeacao', 12, 'text', $TXT$Timeline — título$TXT$, $TXT$Etapas do Concurso$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.timeline.subtitulo', 'campanha-nomeacao', 13, 'text', $TXT$Timeline — subtítulo$TXT$, $TXT$Todas as fases foram cumpridas. Resta apenas o ato administrativo da nomeação.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.viabilidade.label', 'campanha-nomeacao', 14, 'text', $TXT$Viabilidade — eyebrow$TXT$, $TXT$Viabilidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.viabilidade.titulo', 'campanha-nomeacao', 15, 'text', $TXT$Viabilidade — título$TXT$, $TXT$O Custo da Nomeação é Marginal$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.viabilidade.texto', 'campanha-nomeacao', 16, 'markdown', $TXT$Viabilidade — texto$TXT$, $TXT$Frente a um orçamento municipal de **R$ 135 bilhões** e uma despesa de pessoal de **R$ 44 bilhões**, o investimento na nomeação dos 53 aprovados representa uma fração ínfima — com retorno imediato em capacidade de gestão, qualidade técnica e entrega de resultados para a população.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.cta.frase', 'campanha-nomeacao', 17, 'text', $TXT$CTA — frase$TXT$, $TXT$Cada APPGG não nomeado é uma política pública que será coordenada com menos rigor, monitorada com menos precisão e avaliada com menos profundidade.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.cta.assinatura', 'campanha-nomeacao', 18, 'text', $TXT$CTA — assinatura$TXT$, $TXT$Maria Camila Florêncio — Presidente da APOGESP$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('campanha-nomeacao.cta.link', 'campanha-nomeacao', 19, 'text', $TXT$CTA — link$TXT$, $TXT$Apoie a nomeação$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.hero.label', 'publicacoes', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Biblioteca$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.hero.titulo', 'publicacoes', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Publicações$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.hero.subtitulo', 'publicacoes', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$O que a carreira de APPGG pensa, documenta e publica. Artigos, notas técnicas e propostas.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.destaque.label', 'publicacoes', 3, 'text', $TXT$Destaque — eyebrow$TXT$, $TXT$Destaque$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.destaque.titulo', 'publicacoes', 4, 'text', $TXT$Destaque — título$TXT$, $TXT$Caderno Gestão Pública em Rede — 1ª Edição$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.destaque.texto', 'publicacoes', 5, 'markdown', $TXT$Destaque — texto$TXT$, $TXT$Nove artigos. Nove histórias de quem esteve dentro da máquina pública, tentando fazê-la funcionar melhor. A primeira publicação coletiva dos APPGGs celebra uma década de carreira com o que ela faz de melhor: análise rigorosa, experiência de campo e compromisso com o registro. Organizado pela Assessoria de Carreiras Transversais (ACT) da Secretaria Municipal de Gestão.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.destaque.meta', 'publicacoes', 6, 'text', $TXT$Destaque — metadata$TXT$, $TXT$Dezembro 2025 · Prefeitura de São Paulo$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.acervo.label', 'publicacoes', 7, 'text', $TXT$Acervo — eyebrow$TXT$, $TXT$Acervo$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('publicacoes.acervo.titulo', 'publicacoes', 8, 'text', $TXT$Acervo — título$TXT$, $TXT$Documentos Institucionais$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.hero.titulo', 'planos-atuacao', 0, 'text', $TXT$Hero — título$TXT$, $TXT$Planos de Atuação Institucional$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.hero.subtitulo', 'planos-atuacao', 1, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Os PAIs formalizam a demanda de cada órgão por APPGGs, detalhando projetos estratégicos, resultados esperados e competências necessárias. Conheça onde e como os analistas contribuem para a modernização da gestão pública em São Paulo.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.numeros.legenda', 'planos-atuacao', 2, 'text', $TXT$Números — legenda$TXT$, $TXT$APPGGs em exercício por órgão · snapshot de fevereiro de 2026$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.detalhamento.label', 'planos-atuacao', 3, 'text', $TXT$Detalhamento — eyebrow$TXT$, $TXT$Detalhamento$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.detalhamento.titulo', 'planos-atuacao', 4, 'text', $TXT$Detalhamento — título$TXT$, $TXT$Planos por Órgão$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.cta.label', 'planos-atuacao', 5, 'text', $TXT$CTA — eyebrow$TXT$, $TXT$Presença institucional$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.cta.titulo', 'planos-atuacao', 6, 'text', $TXT$CTA — título$TXT$, $TXT$órgãos com planos formalizados$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-atuacao.cta.texto', 'planos-atuacao', 7, 'markdown', $TXT$CTA — texto$TXT$, $TXT$Os Planos de Atuação Institucional são instrumentos vivos. Cada PAI formaliza a demanda estratégica de um órgão por APPGGs, demonstrando o alcance da carreira na modernização da gestão pública de São Paulo.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.hero.label', 'planos-ambientais', 0, 'text', $TXT$Hero — eyebrow$TXT$, $TXT$Sustentabilidade$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.hero.titulo', 'planos-ambientais', 1, 'text', $TXT$Hero — título$TXT$, $TXT$Planos de Atuação com Características Ambientais$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.hero.subtitulo', 'planos-ambientais', 2, 'text', $TXT$Hero — subtítulo$TXT$, $TXT$Recorte dos Planos de Atuação Institucional dos órgãos cuja agenda inclui projetos com dimensão ambiental — clima, infraestrutura sustentável, habitação, saneamento e agricultura urbana.$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.detalhamento.label', 'planos-ambientais', 3, 'text', $TXT$Detalhamento — eyebrow$TXT$, $TXT$Detalhamento$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.detalhamento.titulo', 'planos-ambientais', 4, 'text', $TXT$Detalhamento — título$TXT$, $TXT$Planos por Órgão$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.cta.label', 'planos-ambientais', 5, 'text', $TXT$CTA — eyebrow$TXT$, $TXT$Agenda ambiental$TXT$) on conflict (key) do nothing;
insert into public.page_fields (key, pagina, ordem, tipo, descricao, value_publicado) values ('planos-ambientais.cta.texto', 'planos-ambientais', 6, 'markdown', $TXT$CTA — texto$TXT$, $TXT$Os Planos de Atuação Institucional dos órgãos com características ambientais reúnem projetos voltados a clima, energia, habitação sustentável, infraestrutura urbana e agricultura urbana — todos demandando trabalho técnico colaborativo dos APPGGs.$TXT$) on conflict (key) do nothing;
