WITH seed(ordem, dados) AS (
  VALUES
  (10, '{"recorte":"Brasil","localidade":"Brasil","nome":"Especialista em Políticas Públicas e Gestão Governamental","sigla":"EPPGG","esfera":"Federal","resumo":"Carreira transversal da administração pública federal, voltada à formulação, implementação e avaliação de políticas públicas e ao exercício de atividades de direção e assessoramento.","fonte":"Ministério da Gestão e da Inovação em Serviços Públicos","url":"https://www.gov.br/gestao/pt-br/assuntos/gestao-de-pessoas/carreiras/eppgg","destaque":true}'::jsonb),
  (20, '{"recorte":"Brasil","localidade":"São Paulo — SP","nome":"Analista de Políticas Públicas e Gestão Governamental","sigla":"APPGG","esfera":"Municipal","resumo":"Carreira transversal criada para implementar, coordenar, monitorar e avaliar projetos, atividades e políticas públicas no Município de São Paulo.","fonte":"Lei Municipal nº 16.193/2015","url":"https://legislacao.prefeitura.sp.gov.br/leis/lei-16193-de-5-de-maio-de-2015","destaque":true}'::jsonb),
  (30, '{"recorte":"Brasil","localidade":"Bahia","nome":"Especialista em Políticas Públicas e Gestão Governamental","sigla":"EPPGG","esfera":"Estadual","resumo":"Carreira estadual ligada ao planejamento e à gestão de políticas públicas, com atuação transversal na administração baiana.","fonte":"Governo do Estado da Bahia","url":"https://www.ba.gov.br/administracao/","destaque":false}'::jsonb),
  (40, '{"recorte":"Brasil","localidade":"Mato Grosso","nome":"Gestor Governamental","sigla":"GG","esfera":"Estadual","resumo":"Carreira de gestão governamental do Estado de Mato Grosso, com atribuições relacionadas ao planejamento, à coordenação e à avaliação da ação pública.","fonte":"Governo do Estado de Mato Grosso","url":"https://www.seplag.mt.gov.br/","destaque":false}'::jsonb),
  (50, '{"recorte":"Brasil","localidade":"Minas Gerais","nome":"Especialista em Políticas Públicas e Gestão Governamental","sigla":"EPPGG","esfera":"Estadual","resumo":"Carreira estadual formada em articulação com a Escola de Governo da Fundação João Pinheiro e orientada à gestão e às políticas públicas.","fonte":"Fundação João Pinheiro","url":"https://fjp.mg.gov.br/graduacao/","destaque":false}'::jsonb),
  (60, '{"recorte":"Brasil","localidade":"Distrito Federal","nome":"Políticas Públicas e Gestão Governamental","sigla":"PPGG","esfera":"Distrital","resumo":"Carreira do Distrito Federal com atuação em atividades especializadas de formulação, implementação e avaliação de políticas públicas e gestão governamental.","fonte":"Secretaria de Economia do Distrito Federal","url":"https://www.economia.df.gov.br/","destaque":false}'::jsonb),
  (70, '{"recorte":"Internacional","localidade":"Reino Unido","nome":"Civil Service Fast Stream","sigla":"Fast Stream","esfera":"Nacional","resumo":"Programa de desenvolvimento de lideranças do serviço civil britânico, com trajetórias em diferentes áreas e órgãos governamentais.","fonte":"UK Civil Service","url":"https://www.faststream.gov.uk/","destaque":true}'::jsonb),
  (80, '{"recorte":"Internacional","localidade":"Argentina","nome":"Cuerpo de Administradores Gubernamentales","sigla":"AG","esfera":"Nacional","resumo":"Corpo profissional de administradores governamentais concebido para atuar transversalmente em planejamento, assessoramento e gestão na administração nacional.","fonte":"Argentina.gob.ar","url":"https://www.argentina.gob.ar/jefatura/gestion-y-empleo-publico","destaque":true}'::jsonb),
  (90, '{"recorte":"Internacional","localidade":"Chile","nome":"Sistema de Alta Dirección Pública","sigla":"ADP","esfera":"Nacional","resumo":"Sistema chileno de seleção profissional de dirigentes públicos, referência regional em mérito e gestão de lideranças estatais.","fonte":"Servicio Civil de Chile","url":"https://www.serviciocivil.cl/sistema-de-alta-direccion-publica-2/","destaque":false}'::jsonb),
  (100, '{"recorte":"Internacional","localidade":"Estados Unidos","nome":"Senior Executive Service","sigla":"SES","esfera":"Federal","resumo":"Corpo de liderança executiva da administração federal, situado entre as nomeações políticas e a força de trabalho pública de carreira.","fonte":"U.S. Office of Personnel Management","url":"https://www.opm.gov/policy-data-oversight/senior-executive-service/","destaque":false}'::jsonb),
  (110, '{"recorte":"Internacional","localidade":"Singapura","nome":"Administrative Service","sigla":"AS","esfera":"Nacional","resumo":"Serviço administrativo voltado ao desenvolvimento de lideranças generalistas para funções de formulação e gestão em diferentes órgãos públicos.","fonte":"Public Service Division Singapore","url":"https://www.psd.gov.sg/leadership/public-service-leadership-careers/administrative-service/","destaque":false}'::jsonb)
)
INSERT INTO public.atlas_carreiras (ordem, publicado, deletado, dados_publicado, dados_rascunho, tem_rascunho, updated_by)
SELECT seed.ordem, true, false, seed.dados, null, false, 'seed-atlas-ppgg'
FROM seed
WHERE NOT EXISTS (
  SELECT 1 FROM public.atlas_carreiras existing
  WHERE existing.dados_publicado->>'sigla' = seed.dados->>'sigla'
    AND existing.dados_publicado->>'localidade' = seed.dados->>'localidade'
    AND existing.deletado = false
);